modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Campfire%20Spawn%20and%20Tweaks"
logoFile="icon.png"

[[mods]]
modId="campfirespawnandtweaks"
version="3.4"
displayName="Campfire Spawn and Tweaks"
displayURL="https://curseforge.com/minecraft/mc-mods/campfire-spawn-and-tweaks"
authors="Rick South"
description='''Allows player to set spawn points inside a campfire, gives fire resistance on respawn and does some other tweaks.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.campfirespawnandtweaks]]
    modId="collective"
    mandatory=true
    versionRange="[6.53,)"
    ordering="NONE"
    side="BOTH"